ci(release): auto-release beta with version tag (#3709)
# Motivation

We want to trigger beta release automatically with every new version tag
`v*`

diff --git a/.github/workflows/deploy-to-environment.yml b/.github/workflows/deploy-to-environment.yml
--- a/.github/workflows/deploy-to-environment.yml
+++ b/.github/workflows/deploy-to-environment.yml
@@ -4,6 +4,8 @@ on:
   push:
     branches:
       - main
+    tags:
+      - v[0-9]+.[0-9]+.[0-9]+
   workflow_dispatch:
     inputs:
       network:
@@ -49,11 +51,21 @@ jobs:
       - name: Determine Deployment Network
         run: |
           if [ "${{ github.event_name }}" == "push" ]; then
-            echo "NETWORK=staging" >> $GITHUB_ENV
+            if [ "${{ github.ref_type }}" == "branch" ]; then
+              echo "NETWORK=staging" >> $GITHUB_ENV
+            elif [ "${{ github.ref_type }}" == "tag" ]; then
+              echo "NETWORK=beta" >> $GITHUB_ENV
+            else
+              echo "Error: Unsupported ref type."
+              exit 1
+            fi
             echo "CANISTER=frontend" >> $GITHUB_ENV
           elif [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
             echo "NETWORK=${{ github.event.inputs.network }}" >> $GITHUB_ENV
             echo "CANISTER=${{ github.event.inputs.canister }}" >> $GITHUB_ENV
+          else
+            echo "Error: Unsupported event type."
+            exit 1
           fi
 
       - name: Check release policy
