added caching

diff --git a/.github/workflows/update-snapshots.yml b/.github/workflows/update-snapshots.yml
--- a/.github/workflows/update-snapshots.yml
+++ b/.github/workflows/update-snapshots.yml
@@ -9,7 +9,7 @@ on:
 jobs:
 
   oisy-backend-wasm:
-    runs-on: ubuntu-20.04
+    runs-on: ubuntu-latest
     steps:
       - name: Checkout
         uses: actions/checkout@v4
@@ -21,14 +21,29 @@ jobs:
     runs-on: ubuntu-latest
     needs: oisy-backend-wasm
     steps:
-      - name: Fail if branch is main
-        if: ${{ github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main' }}
-        run: |
-          echo "This workflow should not be triggered with workflow_dispatch on main"
-          exit 1
+
+#      - name: Fail if branch is main
+#        if: ${{ github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main' }}
+#        run: |
+#          echo "This workflow should not be triggered with workflow_dispatch on main"
+#          exit 1
 
       - name: Checkout
         uses: actions/checkout@v4
+
+      - name: Cache Cargo build
+        id: cache
+        uses: actions/cache@v4
+        with:
+          path: |
+            Cargo.toml
+            Cargo.lock
+            rust-toolchain.toml
+            src/backend/
+            src/shared/
+          key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.toml','Cargo.lock','rust-toolchain.toml','src/backend/**/*','src/shared/**/*') }}
+          restore-keys: |
+              ${{ runner.os }}-cargo-
 
       - name: Deploy the backend
         uses: ./.github/actions/deploy-backend
